# Site
site_name: hackettyu's blog
site_url: https://hackettyu.com
site_author: hackettyu
site_description: >-
  hackettyu's blog | hackettyu.repeat( me.eat().sleep().code() )
# Repository
repo_name: hackettyu/hackettyu-mkdocs-material
repo_url: https://github.com/hackettyu/hackettyu-mkdocs-material
edit_uri: "https://github.com/HackettYu/hackettyu-mkdocs-material/blob/master/docs"

# Copyrighpro
copyright: Copyright &copy; 2018 - 2021

# Configuration
theme:
  name: material
  custom_dir: material
  
  # 404 page
  static_templates:
    - 404.html
    - 'html/spotify-user-albums-cover-art.html'
    - 'html/spotify-user-flollow_artists-cover-art.html'
    - 'html/weread-notebook-list-cover-art.html'

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  features:
    - tabs
    - navigation.tabs
    - navigation.instant
    # - navigation.sections
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - search.highlight
    - search.share
    - toc.integrate # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=nav#integrated-table-of-contents
  palette:
    scheme: preference
    primary: white
    accent: indigo
  font:
    text: Noto Sans SC
    code: Fira Code
  icon:
    logo: logo
  favicon: assets/images/favicon.png

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: iso_date
      fallback_to_build_date: true
      enable_creation_date: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hackettyu
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/HackettYu
    - icon: fontawesome/brands/spotify
      link: spotify:user:12glou9s4691jdz6arkbb8zmn
    - icon: fontawesome/solid/rss
      link: https://hackettyu.com/todo
  # https://github.com/squidfunk/mkdocs-material/pull/2363
  analytics:
    provider: google
    property: UA-146236033-1

markdown_extensions:
  - meta
  - codehilite
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: hackettyu
      repo: hackettyu-mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - 2018:
      "0x01-解决 Ubuntu v16.04 没有在打字时停用触摸板选项": 2018-09-13-ubuntu-board.md
      "0x02-用量化自己的代码生涯：用命令行工具 cloc 做代码行统计": 2018-09-27-code-cloc.md
      "0x03-解决 Chromium 浏览器缺少 Google API 密钥无法登录问题": 2018-10-01-chromium-google-api.md
      "0x04-用命令行操作 Window 系统的显卡驱动程序": 2018-10-04-command-close-nvida.md
      "0x05-在命令行下使用 Powershell 提权": 2018-10-04-powershell-upper.md
      "0x06-用 ln 命令了解硬链接和软连接": 2018-10-06-linux-ln.md
      "0x07-我在写 java swap 函数时理解了值传递与引用": 2018-10-18-java-swap-function.md
      "0x08-关于 CentOS 7 新的防火墙命令 firewall-cmd": 2018-10-25-firewall-cmd.md
      "0x09-hexo 配置 DNS 分流导致国内找不到 HOST 的问题处理": 2018-10-25-hexo-dns.md
      "0x10-SSH 登录时出现如下错误：Disconnected:No supported authentication methods available 问题处理": 2018-11-13-ssh-login.md
      "0x11-Windows 下使用 git bash 自带的功能配置终端主题": 2018-12-02-windows-git-bash.md
      "0x12-Eclipse 下切换编译 Java 版本": 2018-12-15-switch-eclipse-version.md
  - 2019:
      "0x01-关于 JavaScript 作用域问题": 2019-01-02-javascript-use.md
      "0x02-JavaScript 错误参考（转载）": 2019-02-16-javascript-error-msg.md
      "0x03-如何订阅一个 Repo 的 Realese 信息：利用 Github API 获取 spring-framework 所有版本更新信息": 2019-04-13-spring-framework-version.md
      "0x04-利用 Tomcat8 和 maven 部署 Web 工程": 2019-04-14-tomcat-deploy-web.md
      "0x05-利用 policy whitelist 解决 Chrome 第三方扩展安装的问题": 2019-09-16-chrome-extention.md
      "0x06-给 hexo 博客添加 OGP 协议支持": 2019-10-30-hexo-ogp.md
      "0x07-如何将 hexo 的 blog 页面发送到 kindle": 2019-11-04-hexo-kindle.md
  - 2020:
      "0x01-命令行下切换当前 workplace 到 Visual Studio Code": 2020-03-20-vscode-diff.md
      "0x02-Windows 下使用 Scoop 工具安装环境以及管理各种软件": 2020-05-07-windows-scoop.md
      "0x03-Mkdocs 搭建博客指北，以及推荐 mkdocs-materials 主题": 2020-06-17-mkdocs-material-turtorial.md
      "0x04-关于 ABAP 的代码缩进风格的思考": 2020-08-20-ABAP-code-indent.md
      "0x05-LightPorxy 的非官方文档": 2020-09-09-lightproxy-unofficial-document.md
      "0x06-Awesome command line slide | 记一次分享命令行的幻灯片": 2020-09-14-awosome-command-line-slide.md
      "0x07-简单使用一下 Python enum": 2020-11-02-python-enum.md
      "0x08-SAP 主数据参考 ｜ SAP MDG API examples": 2020-11-04-sap-mdg-api-example.md
  - 2021:
      "0x01-ABAP 创建一个简单的 RESTful 接口": 2021-01-25-abap-rest-interface.md
      "0x02-用 Python 的 SOAP client Zeep 解析 Webservice 接口": 2021-02-01-zeep-turtorial.md
      "0x03-ABAP REST 工具库 CL_REST_LIBRARY": 2021-02-02-abap-rest-use-library.md
      "0x04-给 Mkdocs 添加 termynal 支持": 2021-02-03-mkdocs-add-termy.md
      "0x05-自用子弹笔记指南": 2021-02-08-bullet-journal-tuturial.md
      "0x06-SAP JCo 例子": 2021-03-31-SAP-JCo-example.md
      "0x07-ABAP WTF 时刻": 2021-06-08-ABAP-WTF.md
      "0x08-Github PR workflow": 2021-06-21-github-pr-workflow.md
      "0x09-关于 ABAP 或许不需要那么多的循环": 2021-06-25-abap-dont-need-many-loops.md
      "0x10-Markdown TIL": 2021-08-30-markdown-TIL.md
  - books:
     ISBN-9787115249494: books/ISBN-9787115249494.md
     ISBN-9787553678054: books/ISBN-9787553678054.md  
     ISBN-9787559627636: books/ISBN-9787559627636.md  
     ISBN-9787559632265: books/ISBN-9787559632265.md  
     ISBN-9787521705041: books/ISBN-9787521705041.md
     ISBN-9787115564672: books/ISBN-9787115564672.md
     ISBN-9787121297267: books/ISBN-9787121297267.md
     ISBN-9787508648286: books/ISBN-9787508648286.md
     ISBN-9787532756728: books/ISBN-9787532756728.md
     ISBN-9787532762897: books/ISBN-9787532762897.md
     ISBN-9787201104560: books/ISBN-9787201104560.md
     ISBN-9787518068715: books/ISBN-9787518068715.md
  - about:
      index: index.md
      cheatsheet: cheatsheet.md
      docs-words: docs/words.md
      what-i-use: what-i-use.md
  - weekly:
      2020-10-0x01: weekly/weekly-2020-10-0x01.md
      2020-10-0x02: weekly/weekly-2020-10-0x02.md
      2020-11-0x01: weekly/weekly-2020-11-0x01.md
      2020-11-0x02: weekly/weekly-2020-11-0x02.md
      2020-11-0x03: weekly/weekly-2020-11-0x03.md
      2020-11-0x04: weekly/weekly-2020-11-0x04.md
      2020-12-0x01: weekly/weekly-2020-12-0x01.md
      2020-12-0x02: weekly/weekly-2020-12-0x02.md
      2020-12-0x03: weekly/weekly-2020-12-0x03.md
      2021-01-0x01: weekly/weekly-2021-01-0x01.md
      2021-01-0x02: weekly/weekly-2021-01-0x02.md
      2021-02-0x01: weekly/weekly-2021-02-0x01.md
      2021-02-0x02: weekly/weekly-2021-02-0x02.md
      2021-02-0x03: weekly/weekly-2021-02-0x03.md
      2021-02-0x04: weekly/weekly-2021-02-0x04.md
      2021-03-0x01: weekly/weekly-2021-03-0x01.md
      2021-03-0x02: weekly/weekly-2021-03-0x02.md
      2021-04-0x01: weekly/weekly-2021-04-0x01.md
      2021-04-0x02: weekly/weekly-2021-04-0x02.md
      2021-06-0x01: weekly/weekly-2021-06-0x01.md
      2021-06-0x02: weekly/weekly-2021-06-0x02.md
      2021-07-0x01: weekly/weekly-2021-07-0x01.md
      2021-07-0x02: weekly/weekly-2021-07-0x02.md
      2021-08-0x01: weekly/weekly-2021-08-0x01.md
      2021-10-0x01: weekly/weekly-2021-10-0x01.md
      2021-12-0x01: weekly/weekly-2021-12-0x01.md

extra_css:
  - '/css/termynal.css'
  - '/css/custom.css'
extra_javascript:
  # baidu stat
  - '/js/baidu-stat.js'
  - '/js/termynal.js'
  - '/js/custom.js'
