# Site
site_name: hackettyu'blog
site_url: https://hackettyu.com
site_author: hackettyu
site_description: >-
  hackettyu.com
# Repository
repo_name: hackettyu/mkdocs-material
repo_url: https://github.com/hackettyu/mkdocs-material
edit_uri: "https://github.com/HackettYu/mkdocs-material/blob/master/docs"

# Copyrighpro
copyright: Copyright &copy; 2018 - 2020

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  features:
    - tabs
    - instant: true
  palette:
    scheme: preference
    primary: white
    accent: indigo
  font:
    text: Noto Sans SC
    code: Fira Code
  icon:
    logo: logo
  favicon: assets/images/favicon.png

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hackettyu
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/spotify
      link: spotify:user:12glou9s4691jdz6arkbb8zmn

# Extensions
markdown_extensions:
  - codehilite
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      hide_protocol: true
      repo_url_shortener: true
      social_url_shortener: true
      shortener_user_exclude: {
        "bitbucket": ['dashboard', 'account', 'plans', 'support', 'repo'],
        "github": ['marketeplace', 'notifications', 'issues', 'pull', 'sponsors', 'settings', 'support'],
        "gitlab": ['dashboard', '-', 'explore', 'help', 'projects'],
        "twitter": ['i', 'messages', 'bookmarks', 'home']
      }
      repo_url_shorthand: true
      social_url_shorthand: true
      provider: true
      user: 'hackettyu'
      repo: ''
      labels: {
          'commit': 'Commit',
          'compare': 'Compare',
          'issue': 'Issue',
          'pull': 'Pull Request',
          'mention': 'User',
          'repository': 'Repository'
      }
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
# nav:
#   - Home: index.md
#   - Getting started: getting-started.md
#   - Extensions:
#     - Admonition: extensions/admonition.md
#     - CodeHilite: extensions/codehilite.md
#     - Footnotes: extensions/footnotes.md
#     - Metadata: extensions/metadata.md
#     - Permalinks: extensions/permalinks.md
#     - PyMdown: extensions/pymdown.md
#   - Plugins:
#     - Search: plugins/search.md
#     - Minification: plugins/minification.md
#     - Revision date: plugins/revision-date.md
#     - Awesome pages: plugins/awesome-pages.md
#   - Releases:
#     - Upgrading to 5.x: releases/5.md
#     - Upgrading to 4.x: releases/4.md
#     - Changelog: releases/changelog.md
#   - Customization: customization.md
#   - Data privacy: data-privacy.md
#   - Contributing: contributing.md
#   - License: license.md

# Google Analytics
google_analytics:
  - UA-146236033-1
  - auto
