# Site
site_name: hackettyu'blog
site_url: https://hackettyu.com
site_author: hackettyu
site_description: >-
  hackettyu'blog | hackettyu.repeat( me.eat().sleep().code() )
# Repository
repo_name: hackettyu/mkdocs-material
repo_url: https://github.com/hackettyu/mkdocs-material
edit_uri: "https://github.com/HackettYu/mkdocs-material/blob/master/docs"

# Copyrighpro
copyright: Copyright &copy; 2018 - 2021

# Configuration
theme:
  name: material
  # custom_dir: material
  

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  # include_search_page: false
  # search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  features:
    - tabs
    - navigation.tabs
    # - instant: true
    # - search.highlight
  palette:
    scheme: preference
    primary: white
    accent: indigo
  font:
    text: Noto Sans SC
    code: Fira Code
  icon:
    logo: logo
  favicon: assets/images/favicon.png

plugins:
  - minify:
      minify_html: true
  - blog:
    - plugin:
        - blog:
            format: "(%m/%d/%y)"
            text-align: "right"
            folder: "docs"


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hackettyu
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/HackettYu
    - icon: fontawesome/brands/spotify
      link: spotify:user:12glou9s4691jdz6arkbb8zmn
    - icon: fontawesome/solid/rss
      link: https://hackettyu.substack.com
# Extensions
markdown_extensions:
  - meta
  - codehilite
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: hackettyu
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# TODO
# nav:
#   - Home: index.md
#   - Weekly: weekly/weekly-2020-10-0x01-.md

google_analytics:
  - UA-146236033-1
  - auto

extra_css:
  - '/css/termynal.css'
  - '/css/custom.css'
extra_javascript:
  # baidu stat
  - '/js/baidu-stat.js'
  - '/js/termynal.js'
  - '/js/custom.js'
