name: Publish docs via GitHub Pages use mike
on:
  push:
    branches:
      # only use in this branch
      - main
    paths:
      - '.github/workflows/document.yml'
      - 'mkdocs.yaml'
      - 'pyproject.toml'
      - 'docs/**'

jobs:
  build:
    name: 
      Deploy docs
    runs-on: 
      ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: git fetch origin doc:doc
      - uses: fregante/setup-git-user@v1

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - uses: actions/cache@v1
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ hashFiles('poetry.lock') }}
      - name: "Setup Poetry"
        run: pip install --user poetry
      - name: "Build Latest Document"
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: |
          poetry install
          # use doc branch
          poetry run mike deploy -b doc --push --update-aliases latest
